// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zF_Tqs-6AHD3qQM4l_AbcptUyfZ8dYk',
    appId: '1:679762706170:web:a0927fe1446ba730759343',
    messagingSenderId: '679762706170',
    projectId: 'sunprojetl3gl',
    authDomain: 'sunprojetl3gl.firebaseapp.com',
    storageBucket: 'sunprojetl3gl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTmfcK-RT3qYT1V08MDRq8mOhlByPqybg',
    appId: '1:679762706170:android:e31790d8c68b2ff4759343',
    messagingSenderId: '679762706170',
    projectId: 'sunprojetl3gl',
    storageBucket: 'sunprojetl3gl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARVHAax7wf7veHnzympcu8Eosi3T5DlIk',
    appId: '1:679762706170:ios:91854dc01409b7af759343',
    messagingSenderId: '679762706170',
    projectId: 'sunprojetl3gl',
    storageBucket: 'sunprojetl3gl.firebasestorage.app',
    iosBundleId: 'com.example.sunuprojetl3gl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARVHAax7wf7veHnzympcu8Eosi3T5DlIk',
    appId: '1:679762706170:ios:91854dc01409b7af759343',
    messagingSenderId: '679762706170',
    projectId: 'sunprojetl3gl',
    storageBucket: 'sunprojetl3gl.firebasestorage.app',
    iosBundleId: 'com.example.sunuprojetl3gl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zF_Tqs-6AHD3qQM4l_AbcptUyfZ8dYk',
    appId: '1:679762706170:web:f426116f3c779a43759343',
    messagingSenderId: '679762706170',
    projectId: 'sunprojetl3gl',
    authDomain: 'sunprojetl3gl.firebaseapp.com',
    storageBucket: 'sunprojetl3gl.firebasestorage.app',
  );
}
